# Generated by Django 5.0.7 on 2024-08-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_bookingdate_booking_bookingdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
