# Generated by Django 5.0.7 on 2024-08-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menuitem_menu_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingdate',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='number_of_guests',
        ),
    ]
